version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./apps/hono-api/src:/usr/src/app/apps/hono-api/src
    ports:
      - "8787:8787"
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=8787
